### ISSUE TITLE
Build breaks with latest logos-docosaurus-preset (1.0.0-alpha.62)

### ISSUE THREAD

**Issue by 0x-r4bbit** [acid-info/logos.co#34]
@amirhouieh pointed out I should use the latest logos docosaurus plugin, which at the time of creating this issue was 1.0.0-alpha.62.

After installing that version and running `yarn start` again, the build seems to fail with:

```
yarn run v1.22.19
$ docusaurus start
[INFO] Starting the development server...
[ERROR] Error: Plugin "docusaurus-theme-mermaid" is used 2 times with ID "default".
To use the same plugin multiple times on a Docusaurus site, you need to assign a unique ID to each plugin instance.

The plugin ID is "default" by default. It's possible that the preset you are using already includes a plugin instance, in which case you either want to disable the plugin in the preset (to use a single instance), or assign another ID to your extra plugin instance (to use multiple instances).
    at /home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:23:23
    at Array.forEach (<anonymous>)
    at /home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:21:45
    at Array.forEach (<anonymous>)
    at ensureUniquePluginInstanceIds (/home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:19:35)
    at initPlugins (/home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/plugins/init.js:92:51)
    at async loadPlugins (/home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/home/rabbit/projects/logos/logos.co/node_modules/@docusaurus/core/lib/commands/start.js:44:19)
[INFO] Docusaurus version: 2.4.1
Node version: v20.3.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 0x-r4bbit** [comment]
@jinhojang6 removing that property from the config solves the issue.
Want me to close this issue or should we wait until this lands in a branch that everyone uses?

**Comment by jinhojang6** [comment]
We can close this but it is up to you :)
